Repository Pews-DEV/book-writer-frontend, pull requests merged in 2022-04, with the labels that each got.

#6 Enhancement register modal responsiviness
  src/components/Modals/RegisterModal/index.jsx
  src/components/Modals/RegisterModal/styles.js
Labels: enhancement, ready to merge

#8 Fix: fixing error in registration modal
  src/components/Modals/RegisterModal/index.jsx
Labels: ready to review, fix

#10 Fix/change context components
  src/components/Hero/index.jsx
  src/components/Modals/RegisterModal/index.jsx
  src/components/Navbar/index.jsx
  src/pages/_app.jsx
  src/pages/home.jsx
  src/screens/home/index.jsx
Labels: ready to review

#12 Implementing login modal
  src/assets/img/logo.png
  src/components/Buttons/index.js
  src/components/Hero/styles.js
  src/components/Modals/LoginModal/index.jsx
  src/components/Modals/LoginModal/index.test.js
  src/components/Modals/RegisterModal/index.jsx
  src/components/Modals/RegisterModal/styles.js
  src/components/Modals/styles.js
  src/components/Navbar/index.jsx
  src/styles/globals.js
Labels: ready to review, feature

#13 Feature/pipeline with coverage
  .github/workflows/ci.yml
  jest.config.js
  package.json
  public/sw.js
  public/workbox-5afaf374.js
  src/components/Modals/LoginModal/index.jsx
  src/components/Modals/index.jsx
  src/components/Modals/index.test.jsx
  src/components/Navbar/index.jsx
  src/components/Navbar/index.test.jsx
  src/screens/home/index.test.jsx
  src/styles/Containers.js
  src/tests/pages/Home.test.jsx
  src/tests/pages/_app.test.jsx
  src/tests/styles/FullyContainer.test.jsx
  src/tests/styles/GlobalStyles.test.jsx
  src/tests/styles/MainContainer.test.jsx
Labels: ready to review, feature, build

#17 Adding Proptypes in components
  src/components/Modals/LoginModal/index.jsx
  src/components/Modals/LoginModal/proptypes.js
  src/components/Modals/RegisterModal/index.jsx
  src/components/Modals/RegisterModal/proptypes.js
  src/components/Modals/index.jsx
  src/components/Modals/proptypes.js
  src/styles/Containers.js
  src/styles/PropTypes/Containers.Proptypes.js
Labels: enhancement, ready to review, feature

#16 Feat/add icon show password
  src/assets/img/close-eye.png
  src/assets/img/eye.png
  src/components/Inputs/index.jsx
  src/components/Inputs/index.test.js
  src/components/Inputs/proptypes.js
  src/components/Inputs/styles.js
  src/components/Modals/LoginModal/index.jsx
  src/components/Modals/LoginModal/index.test.js
  src/components/Modals/RegisterModal/index.jsx
  src/components/Modals/styles.js
Labels: ready to merge, feature
